//
// File: state_file.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 28-Apr-2023 18:16:06
//

// Include Files
#include "state_file.h"
#include <math.h>

// Function Definitions
//
// STATE_FILE
//     D_STATE = STATE_FILE(DTHETA,DX,F,G,L,M1,M2,THETA)
//
// Arguments    : double Dtheta
//                double Dx
//                double F
//                double g
//                double l
//                double m1
//                double m2
//                double theta
//                double d_state[4]
// Return Type  : void
//
void state_file(double Dtheta, double Dx, double F, double g, double l,
                double m1, double m2, double theta, double d_state[4])
{
  double b_d_state_tmp;
  double d_state_tmp;
  double t11;
  double t2;
  double t3;
  double t4;
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     28-Apr-2023 18:14:59
  t2 = cos(theta);
  t3 = sin(theta);
  t4 = Dtheta * Dtheta;
  t11 = 1.0 / ((m1 * 4.0 + m2 * 4.0) + -(m2 * (t2 * t2) * 3.0));
  d_state[0] = Dtheta;
  d_state_tmp = g * m2;
  b_d_state_tmp = l * m2;
  d_state[1] = t11 *
               (((F * t2 * 2.0 + g * m1 * t3) + d_state_tmp * t3) +
                b_d_state_tmp * t2 * t3 * t4 * 2.0) *
               -1.5 / l;
  d_state[2] = Dx;
  d_state[3] = t11 *
               ((F * 8.0 + d_state_tmp * t2 * t3 * 3.0) +
                b_d_state_tmp * t3 * t4 * 8.0) /
               2.0;
}

//
// File trailer for state_file.cpp
//
// [EOF]
//
