//
// File: myfile.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 18-Apr-2023 16:19:39
//

// Include Files
#include "myfile.h"
#include <cmath>

// Function Definitions
//
// MYFILE
//     JAC_MAT = MYFILE(DTHETA,F,G,L,M1,M2,THETA)
//
// Arguments    : double Dtheta
//                double F
//                double g
//                double l
//                double m1
//                double m2
//                double theta
//                double jac_mat[20]
// Return Type  : void
//
void myfile(double Dtheta, double F, double g, double l, double m1, double m2,
            double theta, double jac_mat[20])
{
  double b_jac_mat_tmp;
  double c_jac_mat_tmp;
  double d_jac_mat_tmp;
  double e_jac_mat_tmp;
  double f_jac_mat_tmp;
  double jac_mat_tmp;
  double t11;
  double t12;
  double t2;
  double t3;
  double t4;
  double t6;
  double t7;
  double t8;
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     18-Apr-2023 15:43:31
  t2 = std::cos(theta);
  t3 = std::sin(theta);
  t4 = Dtheta * Dtheta;
  t7 = 1.0 / l;
  t6 = t3 * t3;
  t8 = m2 * (t2 * t2);
  t11 = 1.0 / ((m1 + m2) + -t8);
  t12 = t11 * t11;
  jac_mat[0] = 0.0;
  jac_mat[1] = -t2 * t7 * t11;
  jac_mat[2] = 0.0;
  jac_mat[3] = t11;
  jac_mat[4] = 0.0;
  jac_mat_tmp = g * m1;
  b_jac_mat_tmp = g * m2;
  c_jac_mat_tmp = l * m2;
  d_jac_mat_tmp = c_jac_mat_tmp * t2;
  e_jac_mat_tmp = m2 * t2 * t3;
  f_jac_mat_tmp = b_jac_mat_tmp * t2;
  jac_mat[5] =
      -t7 * t11 *
          ((((-F * t3 + jac_mat_tmp * t2) + f_jac_mat_tmp) + l * t4 * t8) -
           c_jac_mat_tmp * t4 * t6) +
      e_jac_mat_tmp * t7 * t12 *
          (((F * t2 + jac_mat_tmp * t3) + b_jac_mat_tmp * t3) +
           d_jac_mat_tmp * t3 * t4) *
          2.0;
  jac_mat[6] = 0.0;
  jac_mat[7] = t11 * ((g * t8 - b_jac_mat_tmp * t6) + d_jac_mat_tmp * t4) -
               e_jac_mat_tmp * t12 *
                   ((F + f_jac_mat_tmp * t3) + c_jac_mat_tmp * t3 * t4) * 2.0;
  jac_mat[8] = 1.0;
  jac_mat[9] = Dtheta * m2 * t2 * t3 * t11 * -2.0;
  jac_mat[10] = 0.0;
  jac_mat[11] = Dtheta * l * m2 * t3 * t11 * 2.0;
  jac_mat[12] = 0.0;
  jac_mat[13] = 0.0;
  jac_mat[14] = 0.0;
  jac_mat[15] = 0.0;
  jac_mat[16] = 0.0;
  jac_mat[17] = 0.0;
  jac_mat[18] = 1.0;
  jac_mat[19] = 0.0;
}

//
// File trailer for myfile.cpp
//
// [EOF]
//
