namespace OSGIEVENT
{
const char MOUSE_PRESSED[]="MOUSE_PRESSED";
const char TCPHEXRECIEVED[]="TCPHEXRECIEVED";
const char MAT_GET_NOW[]="MAT_GET_NOW";
const char GET_PENDULUM_STATE_NOW[]="GET_PENDULUM_STATE_NOW";
const char SEND_PENDULUM_ACTION_NOW[]="SEND_PENDULUM_ACTION_NOW";
const char REQUEST_PUSHINGBOX_STATE_NOW[]="REQUEST_PUSHINGBOX_STATE_NOW";
const char RETURN_PUSHINGBOX_STATE_NOW[]="RETURN_PUSHINGBOX_STATE_NOW";
const char ACTION_PUSHINGBOX[]="ACTION_PUSHINGBOX";

}
