namespace OSGIEVENT
{
const char MOUSE_PRESSED[]="MOUSE_PRESSED";
const char TCPHEXRECIEVED[]="TCPHEXRECIEVED";
const char MAT_GET_NOW[]="MAT_GET_NOW";
const char GET_PENDULUM_STATE_NOW[]="GET_PENDULUM_STATE_NOW";
const char SEND_PENDULUM_ACTION_NOW[]="SEND_PENDULUM_ACTION_NOW";
const char REQUEST_PUSHINGBOX_STATE_NOW[]="REQUEST_PUSHINGBOX_STATE_NOW";
const char RETURN_PUSHINGBOX_STATE_NOW[]="RETURN_PUSHINGBOX_STATE_NOW";
const char ACTION_PUSHINGBOX[]="ACTION_PUSHINGBOX";

const char SIG_MAP_SELECT_POINTS[]="SIG_MAP_SELECT_POINTS";
const char SIG_MAP_STOP_SELECT_POINTS[]="SIG_MAP_STOP_SELECT_POINTS";
const char SIG_MAP_AUTONAVIGATE_POINTS[]="SIG_MAP_AUTONAVIGATE_POINTS";

const char SIG_AGENT_STATE_UPDATE[]="SIG_AGENT_STATE_UPDATE";
const char SIG_OBS_STATE_UPDATE[]="SIG_OBS_STATE_UPDATE";

const char UWB_AGENT_STATE_UPDATE[]="UWB_AGENT_STATE_UPDATE";

const char SIG_SWARMSIMULATOR_SIGSTART[]="SIG_SWARMSIMULATOR_SIGSTART";
const char SIG_SWARMSIMULATOR_SIGSTOP[]="SIG_SWARMSIMULATOR_SIGSTOP";
const char SIG_SWARMSIMULATOR_SIGSPIN[]="SIG_SWARMSIMULATOR_SIGSPIN";
const char SIG_SWARMSIMULATOR_SIGCHOOSE[]="SIG_SWARMSIMULATOR_SIGCHOOSE";
const char SIG_SWARMSIMULATOR_SIGSHOWSTARTWINDOW[]="SIG_SWARMSIMULATOR_SIGSHOWSTARTWINDOW";

}
